apiVersion: v1
kind: Service

metadata:
  name: ai-research-assistant-service

spec:
  selector:
    app: ai-research-assistant

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

  type: NodePort